name: Tracking PR Mutants

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "**.rs"

concurrency:
  group: filter-pr-${{ github.head_ref || github.ref || github.run_id }}
  # Always cancel duplicate jobs
  cancel-in-progress: true

jobs:
  # Check whether there are differences on `stackslib`, `stacks-node` or `clarity` packages (bigger ones) and whether to run the mutants using shards or not
  check-big-packages-and-shards:
    name: Check Packages and Shards

    runs-on: ubuntu-latest

    outputs:
      big_packages: ${{ steps.check_big_packages.outputs.packages_output }}
      shards_needed: ${{ steps.check_big_packages.outputs.shards_output }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: cargo install --git https://github.com/sourcefrog/cargo-mutants cargo-mutants

      - id: check_big_packages
        run: |
          git diff origin/${{ github.base_ref }}.. > git.diff
          big_packages_found="false"

          if [[ $(cargo mutants --in-diff git.diff --list | grep 'stackslib\|stacks-node') ]]; then
            big_packages_found="true"
            echo "packages_output=true" >> "$GITHUB_OUTPUT"
          else
            echo "packages_output=false" >> "$GITHUB_OUTPUT"
          fi

          if [[ $(cargo mutants --in-diff git.diff --list | awk 'END { print NR }' | tr -d '[:space:]') -gt 40 && "$big_packages_found" == "false" ]]; then
            echo "shards_output=true" >> "$GITHUB_OUTPUT"
          elif [[ $(cargo mutants --in-diff git.diff --list | awk 'END { print NR }' | tr -d '[:space:]') -gt 8 && "$big_packages_found" == "true" ]]; then
            echo "shards_output=true" >> "$GITHUB_OUTPUT"
          else
            echo "shards_output=false" >> "$GITHUB_OUTPUT"
          fi

  # Mutation testing - Execute on PR on packages that have functions modified (normal run, no shards)
  filter-pr-mutants-normal:
    name: Incremental Mutants Testing - Normal

    needs: check-big-packages-and-shards

    if: ${{ needs.check-big-packages-and-shards.outputs.shards_needed == 'false' }}

    runs-on: ubuntu-latest

    steps:
      - name: Run filtering pr mutants from actions - no shards, big packages
        if: ${{ needs.check-big-packages-and-shards.outputs.big_packages == 'true' }}
        env:
          BITCOIND_TEST: 1
          RUST_BACKTRACE: full
        uses: ASuciuX/actions/mutation-testing/filter-pr@test/modular-mutants-runs
        with:
          contains-big-package: true

      - name: Run filtering pr mutants from actions - no shards, normal packages
        if: ${{ needs.check-big-packages-and-shards.outputs.big_packages == 'false' }}
        uses: ASuciuX/actions/mutation-testing/filter-pr@test/modular-mutants-runs
        with:
          contains-big-package: false

  # Mutation testing - Execute on PR on packages that have functions modified (run with strategy matrix shards)
  filter-pr-mutants-shards:
    name: Incremental Mutants Testing - Shards

    needs: check-big-packages-and-shards

    if: ${{ needs.check-big-packages-and-shards.outputs.shards_needed == 'true' }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shard: [0, 1, 2, 3, 4, 5, 6, 7]

    steps:
      - name: Run filtering pr mutants from actions - with shards, big packages
        if: ${{ needs.check-big-packages-and-shards.outputs.big_packages == 'true' }}
        env:
          BITCOIND_TEST: 1
          RUST_BACKTRACE: full
        uses: ASuciuX/actions/mutation-testing/filter-pr@test/modular-mutants-runs
        with:
          shard: ${{ matrix.shard }}
          contains-big-package: true

      - name: Run filtering pr mutants from actions - with shards, normal packages
        if: ${{ needs.check-big-packages-and-shards.outputs.big_packages == 'false' }}
        uses: ASuciuX/actions/mutation-testing/filter-pr@test/modular-mutants-runs
        with:
          shard: ${{ matrix.shard }}
          contains-big-package: false

  # Output the mutants and fail the workflow if there are missed/timeout/unviable mutants
  output-mutants:
    name: Output Mutants

    runs-on: ubuntu-latest

    if: always()
    needs: [filter-pr-mutants-normal, filter-pr-mutants-shards]

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Delete artifacts from workflow
        uses: geekyeggo/delete-artifact@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: |
            mutants-shard--1
            mutants-shard-0
            mutants-shard-1
            mutants-shard-2
            mutants-shard-3
            mutants-shard-4
            mutants-shard-5
            mutants-shard-6
            mutants-shard-7
          failOnError: false

      - name: Append output from all shards
        run: |
          folders=("mutants-shard--1" "mutants-shard-0" "mutants-shard-1" "mutants-shard-2" "mutants-shard-3" "mutants-shard-4" "mutants-shard-5" "mutants-shard-6" "mutants-shard-7")
          files=("missed.txt" "caught.txt" "timeout.txt" "unviable.txt")
          mkdir -p mutants-shards

          for file in "${files[@]}"; do
            for folder in "${folders[@]}"; do
              if [[ -s "$folder" ]]; then
                cat "$folder/$file" >> "mutants-shards/$file"
              fi
            done
          done

          for folder in "${folders[@]}"; do
            if [[ -s "$folder" ]]; then
              exit_code=$(<"${folder}/exit_code.txt")
              most_relevant_exit_code=0

              case $exit_code in
              4)
                most_relevant_exit_code=4
                ;;
              1)
                [ "$most_relevant_exit_code" -eq 0 ] && most_relevant_exit_code=1
                ;;
              2)
                [ "$most_relevant_exit_code" -eq 0 ] && most_relevant_exit_code=2
                ;;
              3)
                [ "$most_relevant_exit_code" -eq 0 ] && most_relevant_exit_code=3
                ;;
              0)
                ;;
              *)
                echo "Unknown exit code $exit_code"
                most_relevant_exit_code=$exit_code
                ;;
              esac
            fi
          done

          echo "$most_relevant_exit_code" > './mutants-shards/exit_code.txt'

      - name: Print mutants and handle exit codes
        run: |
          server_url="${{ github.server_url }}"
          organisation="${{ github.repository_owner }}"
          repository="${{ github.event.repository.name }}"
          commit="${{ github.sha }}"

          write_section() {
            local section_title=$1
            local file_name=$2

            if [ -s "$file_name" ]; then
              if [[ "$section_title" != "" ]]; then
                echo "## $section_title" >> "$GITHUB_STEP_SUMMARY"
              fi

              if [[ "$section_title" == "Missed:" ]]; then
                echo "<details>" >> "$GITHUB_STEP_SUMMARY"
                echo "<summary>What are missed mutants?</summary>" >> "$GITHUB_STEP_SUMMARY"
                echo "<br>" >> "$GITHUB_STEP_SUMMARY"
                echo "No test failed with this mutation applied, which seems to indicate a gap in test coverage. Or, it may be that the mutant is undistinguishable from the correct code. You may wish to add a better test, or mark that the function should be skipped." >> "$GITHUB_STEP_SUMMARY"
                echo "</details>" >> "$GITHUB_STEP_SUMMARY"
                echo "" >> "$GITHUB_STEP_SUMMARY"
              elif [[ "$section_title" == "Timeout:" ]]; then
                echo "<details>" >> "$GITHUB_STEP_SUMMARY"
                echo "<summary>What are timeout mutants?</summary>" >> "$GITHUB_STEP_SUMMARY"
                echo "<br>" >> "$GITHUB_STEP_SUMMARY"
                echo "The mutation caused the test suite to run for a long time, until it was eventually killed. You might want to investigate the cause and potentially mark the function to be skipped." >> "$GITHUB_STEP_SUMMARY"
                echo "</details>" >> "$GITHUB_STEP_SUMMARY"
                echo "" >> "$GITHUB_STEP_SUMMARY"
              elif [[ "$section_title" == "Unviable:" ]]; then
                echo "<details>" >> "$GITHUB_STEP_SUMMARY"
                echo "<summary>What are unviable mutants?</summary>" >> "$GITHUB_STEP_SUMMARY"
                echo "<br>" >> "$GITHUB_STEP_SUMMARY"
                echo "The attempted mutation doesn't compile. This is inconclusive about test coverage and no action is needed, unless you wish to test the specific function, in which case you may wish to add a 'Default::default()' implementation for the specific return type." >> "$GITHUB_STEP_SUMMARY"
                echo "</details>" >> "$GITHUB_STEP_SUMMARY"
                echo "" >> "$GITHUB_STEP_SUMMARY"
              fi

              if [[ "$section_title" != "" ]]; then
                awk -F':' '{printf "- [ ] " "[" $0 "]"; file_path=$1; line=$2; $1=""; $2=""; printf "(" "'"$server_url"'/'"$organisation"'/'"$repository"'/blob/'"$commit"'/" file_path "#L" line-1 ")\n\n"}' "$file_name" >> "$GITHUB_STEP_SUMMARY"
              else
                awk -F':' '{printf "- [x] " "[" $0 "]"; file_path=$1; line=$2; $1=""; $2=""; printf "(" "'"$server_url"'/'"$organisation"'/'"$repository"'/blob/'"$commit"'/" file_path "#L" line-1 ")\n\n"}' "$file_name" >> "$GITHUB_STEP_SUMMARY"
              fi

              if [[ "$section_title" == "Missed:" ]]; then
                echo "### To resolve this issue, consider one of the following options:" >> "$GITHUB_STEP_SUMMARY"
                echo "- Modify or add tests including this function." >> "$GITHUB_STEP_SUMMARY"
                echo "- If you are absolutely certain that this function should not undergo mutation testing, add '#[mutants::skip]' or '#[cfg_attr(test, mutants::skip)]' function header to skip it." >> "$GITHUB_STEP_SUMMARY"
              elif [[ "$section_title" == "Timeout:" ]]; then
                echo "### To resolve this issue, consider one of the following options:" >> "$GITHUB_STEP_SUMMARY"
                echo "- Modify the tests that include this funcion." >> "$GITHUB_STEP_SUMMARY"
                echo "- Add '#[mutants::skip]' or '#[cfg_attr(test, mutants::skip)]' function header to skip it." >> "$GITHUB_STEP_SUMMARY"
              elif [[ "$section_title" == "Unviable:" ]]; then
                echo "### To resolve this issue, consider one of the following options:" >> "$GITHUB_STEP_SUMMARY"
                echo "- Create 'Default::default()' implementation for the specific structure." >> "$GITHUB_STEP_SUMMARY"
                echo "- Add '#[mutants::skip]' or '#[cfg_attr(test, mutants::skip)]' function header to skip it." >> "$GITHUB_STEP_SUMMARY"
              fi

              echo >> "$GITHUB_STEP_SUMMARY"
            fi
          }

          echo "# Uncaught Mutants" >> "$GITHUB_STEP_SUMMARY"
          write_section "Missed:" "./mutants-shards/missed.txt"
          write_section "Timeout:" "./mutants-shards/timeout.txt"
          write_section "Unviable:" "./mutants-shards/unviable.txt"
            
          echo "# Caught Mutants" >> "$GITHUB_STEP_SUMMARY"
          write_section "" "./mutants-shards/caught.txt"

          exit_code=$(<"mutants-shards/exit_code.txt")

          case $exit_code in
            0)
                if [ -s ./mutants-shards/unviable.txt ]; then
                  echo "Found unviable mutants!"
                  exit 1
                fi
              echo "All new and updated functions are caught!"
              ;;
            1)
              echo "Invalid command line arguments!"
              exit 1
              ;;
            2 | 3)
              echo "Found missed/timeout/unviable mutants!"
              exit 1
              ;;
            4)
              echo "Building the packages failed without any mutations!"
              exit 1
              ;;
            *)
              echo "Unknown exit code: $exit_code"
              exit 1
            ;;
          esac
