name: Tracking PR Mutants

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "**.rs"

concurrency:
  group: filter-pr-${{ github.head_ref || github.ref || github.run_id }}
  # Always cancel duplicate jobs
  cancel-in-progress: true

jobs:
  # Mutants testing: Execute on PR on packages that have functions modified, and fail the workflow if there are missed or timeout mutations
  incremental-mutants:
    name: Incremental Mutants Testing

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shard: [0, 1, 2, 3, 4, 5, 6, 7]

    steps:
      - name: Run filtering pr mutants from actions
        uses: ASuciuX/actions/mutation-testing/filter-pr@test/shards-mutants
        with:
          shard: ${{ matrix.shard }}

  # Output the mutants if there are missed/timeout/unviable
  output-mutants:
    name: Output Mutants

    runs-on: ubuntu-latest

    if: always()
    needs: [incremental-mutants]

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Delete artifacts from workflow
        uses: geekyeggo/delete-artifact@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: |
            mutants-shard-0
            mutants-shard-1
            mutants-shard-2
            mutants-shard-3
            mutants-shard-4
            mutants-shard-5
            mutants-shard-6
            mutants-shard-7
          failOnError: false

      - name: Append output from all shards
        run: |
          folders=("mutants-shard-0" "mutants-shard-1" "mutants-shard-2" "mutants-shard-3" "mutants-shard-4" "mutants-shard-5" "mutants-shard-6" "mutants-shard-7")
          files=("missed.txt" "caught.txt" "timeout.txt" "unviable.txt")
          mkdir -p mutants-shards

          for file in "${files[@]}"; do
            for folder in "${folders[@]}"; do
              cat "$folder/$file" >> "mutants-shards/$file"
            done
          done

          for folder in "${folders[@]}"; do
            exit_code=$(<"${folder}/exit_code.txt")
            most_relevant_exit_code=0

            case $exit_code in
            4)
                most_relevant_exit_code=4
                ;;
            1)
                [ "$most_relevant_exit_code" -eq 0 ] && most_relevant_exit_code=1
                ;;
            2)
                [ "$most_relevant_exit_code" -eq 0 ] && most_relevant_exit_code=2
                ;;
            3)
                [ "$most_relevant_exit_code" -eq 0 ] && most_relevant_exit_code=3
                ;;
            0)
                ;;
            *)
                echo "Unknown exit code $exit_code"
                most_relevant_exit_code=$exit_code
                ;;
            esac
          done

          echo "$most_relevant_exit_code" > './mutants-shards/exit_code.txt'

      - name: Print mutants and handle exit codes
        run: |
          server_url="${{ github.server_url }}"
          organisation="$ORGANIZATION_VAR"
          repository="$REPOSITORY_VAR"
          commit="${{ github.sha }}"
            
          write_section() {
            local section_title=$1
            local file_name=$2
            
            if [ -s "$file_name" ]; then
              if [[ "$section_title" != "" ]]; then
                echo "## $section_title" >> "$GITHUB_STEP_SUMMARY"
              fi
                    
              if [[ "$section_title" != "" ]]; then
                awk -F':' '{printf "- [ ] " "[" $0 "]"; file_path=$1; line=$2; $1=""; $2=""; printf "(" "'"$server_url"'/'"$organisation"'/'"$repository"'/blob/'"$commit"'/" file_path "#L" line-1 ")\n\n"}' "$file_name" >> "$GITHUB_STEP_SUMMARY"
              else
                awk -F':' '{printf "- [x] " "[" $0 "]"; file_path=$1; line=$2; $1=""; $2=""; printf "(" "'"$server_url"'/'"$organisation"'/'"$repository"'/blob/'"$commit"'/" file_path "#L" line-1 ")\n\n"}' "$file_name" >> "$GITHUB_STEP_SUMMARY"
              fi
            
              if [[ "$section_title" == "Missed:" ]]; then
                echo "### To resolve this issue, consider one of the following options:" >> "$GITHUB_STEP_SUMMARY"
                echo "- Modify or add tests including this function." >> "$GITHUB_STEP_SUMMARY"
                echo "- Add '#[mutants::skip]' or '#[cfg_attr(test, mutants::skip)]' function header in order to skip it." >> "$GITHUB_STEP_SUMMARY"
              elif [[ "$section_title" == "Timeout:" ]]; then
                echo "### To resolve this issue, consider one of the following options:" >> "$GITHUB_STEP_SUMMARY"
                echo "- Modify the tests that include this funcion." >> "$GITHUB_STEP_SUMMARY"
                echo "- Add '#[mutants::skip]' or '#[cfg_attr(test, mutants::skip)]' function header in order to skip it." >> "$GITHUB_STEP_SUMMARY"
              elif [[ "$section_title" == "Unviable:" ]]; then
                echo "### To resolve this issue, consider one of the following options:" >> "$GITHUB_STEP_SUMMARY"
                echo "- Create 'Default::default()' implementation for the specific structure." >> "$GITHUB_STEP_SUMMARY"
                echo "- Add '#[mutants::skip]' or '#[cfg_attr(test, mutants::skip)]' function header in order to skip it." >> "$GITHUB_STEP_SUMMARY"
              fi
                    
              echo >> "$GITHUB_STEP_SUMMARY"
            fi
          }
            
          echo "# Uncaught Mutants" >> "$GITHUB_STEP_SUMMARY"
          write_section "Missed:" "../../../Downloads/mutants-shards/missed.txt"
          write_section "Timeout:" "../../../Downloads/mutants-shards/timeout.txt"
          write_section "Unviable:" "../../../Downloads/mutants-shards/unviable.txt"
            
          echo "# Caught Mutants" >> "$GITHUB_STEP_SUMMARY"
          write_section "" "../../../Downloads/mutants-shards/caught.txt"

          exit_code=$(<"mutants-shards/exit_code.txt")

          case $exit_code in
            0)
                if [ -s ./mutants-shards/unviable.txt ]; then
                  echo "Found unviable mutants!"
                  exit 1
                fi
              echo "All new and updated functions are caught!"
              ;;
            1)
              echo "Invalid command line arguments!"
              exit 1
              ;;
            2 | 3)
              echo "Found missed/timeout/unviable mutants!"
              exit 1
              ;;
            4)
              echo "Building the packages failed without any mutations!"
              exit 1
              ;;
            *)
              echo "Unknown exit code: $exit_code"
              exit 1
            ;;
          esac
