name: Test actions

on:
  workflow_dispatch:

jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Call action
        uses: ASuciuX/actions/mutation-testing/test-action@feat/mutation-testing
